example_site/example_site/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("geography.urls")),
]

example_site/geography/urls.py
from django.urls import path

from geography.views import (
    ContinentListView,
    ContinentDetailView,
    CountryDetailView,
    CityDetailView,
)

urlpatterns = [
    path("", ContinentListView.as_view(), name="continent-list"),
    path(
        "<slug:slug>/",
        ContinentDetailView.as_view(),
        name="continent-detail",
    ),
    path(
        "<slug:continent_slug>/<slug:slug>/",
        CountryDetailView.as_view(),
        name="country-detail",
    ),
    path(
        "<slug:continent_slug>/<slug:country_slug>/<slug:slug>/",  # noqa
        CityDetailView.as_view(),
        name="city-detail",
    ),
]

example_site/geography/models.py
from django.db import models
from django.urls import reverse


class BaseModel(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(default="", editable=True, max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class Continent(BaseModel):
    def get_absolute_url(self):
        kwargs = {"continent_slug": self.slug}
        return reverse("continent-detail", kwargs=kwargs)


class Country(BaseModel):
    continent = models.ForeignKey(
        Continent,
        on_delete=models.CASCADE,
    )


class City(BaseModel):
    country = models.ForeignKey(
        Country,
        on_delete=models.CASCADE,
    )

example_site/geography/views.py
from django.shortcuts import get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from geography.models import Continent, Country, City


class ContinentListView(ListView):
    model = Continent
    

class ContinentDetailView(DetailView):
    model = Continent

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["continent_slug"] = self.kwargs.get("slug")
        return context

class CountryDetailView(DetailView):
    model = Country
    slug_field = "slug"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["continent_slug"] = self.kwargs.get("continent_slug")
        context["country_slug"] = self.kwargs.get("slug")
        return context

class CityDetailView(DetailView):
    model = City

example_site/geography/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
	<title>{% block title %}Geography site{% endblock %}</title>
    </head>

    <body>
	<h1>{% block header %} Geography {% endblock %}</h1>
	<div id="content">
            {% block content %}{% endblock %}
	</div>
	<hr>
	<h2>Breadcrumbs</h2>
	{% if breadcrumbs %}
	<div class="container">
	    {% include "dynamic_breadcrumbs/breadcrumbs.html" with breadcrumbs=breadcrumbs%}
	</div>
	{% endif %}

    </body>
</html>

example_site/geography/templates/geography/city_detail.html
{% extends "base.html" %}

{% block title %}City detail{% endblock %}
{% block header %}{{object.name}}{% endblock %}

{% block content %}

{% endblock %}

example_site/geography/templates/geography/continent_detail.html
{% extends "base.html" %}

{% block title %}Continent detail{% endblock %}
{% block header %}{{object.name}}{% endblock %}

{% block content %}
<ul>
    {% for object in object.country_set.all %}
    <li>
	<a href="{% url 'country-detail' continent_slug=continent_slug slug=object.slug%}">
	    {{ object.name }}
	</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

example_site/geography/templates/geography/continent_list.html
{% extends "base.html" %}

{% block title %}Continent list{% endblock %}
{% block header %}Continent list{% endblock %}

{% block content %}
<ul>
    {% for object in object_list %}
    <li><a href="{% url 'continent-detail' slug=object.slug%}">{{ object.name }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

example_site/geography/templates/geography/country_detail.html
{% extends "base.html" %}

{% block title %}Country detail{% endblock %}
{% block header %}{{object.name}}{% endblock %}

{% block content %}
<ul>
    {% for object in object.city_set.all %}
    <li>
	<a href="{% url 'city-detail' continent_slug=continent_slug country_slug=country_slug slug=object.slug%}">
	    {{ object.name }}
	</a>
    </li>
    {% endfor %}
</ul>
{% endblock %}